### ISSUE TITLE
2nd mesh. Rabbitmq with secrets

### ISSUE THREAD

**Issue by raphaelcervantes** [driplineorg/controls-guide#9]
I configured the rabbitmq pod from the [bitnami helm chart](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq/) to use a secret password. I can do a pull request with these changes if there is interest.

I'm pasting my config files below. Do the dripline maintainers find the conventions to be ok? Another possibility is to make the user create the secret imperatively.

### rabbitmq-login-secret.yaml

```
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-app
type: Opaque
data:
  rabbitmq-password: cGFzc3dvcmQ=
  rabbitmq-erlang-cookie: cGFzc3dvcmQ=
```

### rabbitmq-values.yaml 
```
replicas: 1

rabbitmq:
  username: dripline
  existingPasswordSecret: rabbitmq-app
  existingErlangSecret: rabbitmq-app

persistence:
  enabled: false
```
